### PR TITLE
Fixes for elec messages

### PR DESCRIPTION
**Pull request by erspearson**
Corrections to the generation of event names for registering and
de-registering of 'elec' events from the underlying rfxcom library.

### CODE REVIEW

**Comment by erspearson** [comment]
My first time checking out node-red. Thought I'd plot my electricity consumption from an Owl monitor via an RfxTrx. No luck at first. Dug a little deeper and found some issues with the generation of the names of events for the 'elec' messages and also non-matching de-registration.

This is also my first ever Git pull request! (despite being in my 4th decade of programming, ouch).
See what you think...

**Comment by erspearson** [comment]
Don't think I was supposed to 'close' this - new to GitHub.

**Comment by maxwellhadley** [comment]
Just back from holiday to find this PR. Embarrassingly obvious once it's pointed out - many thanks!

**Comment by erspearson** [comment]
I assumed you done it deliberately as an exercise for someone new to node, nodered, npm etc to achieve the important learning milestone/epiphany of leaving the 'zone of confusion' and arriving at the plateaux of 'no it's not me that's confused, it really is an actual bug'. :-)

**Pull request merged**
